export enum NotificationType {
  // Campaign events
  CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED',
  CAMPAIGN_STARTED = 'CAMPAIGN_STARTED',
  CAMPAIGN_PAUSED = 'CAMPAIGN_PAUSED',
  CAMPAIGN_FAILED = 'CAMPAIGN_FAILED',
  // Future: Add more types here
  // SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
  // CONTACT_IMPORT_COMPLETED = 'CONTACT_IMPORT_COMPLETED',
}

